"""docs.py: command docs parsed from a generated RizomUVLinkBase.py."""

import json

import pytest

from rizomuv_mcp import docs

GENERATED = (
    "# File generated by RizomUV 2027.0.486.gf16af8f9 built on Sep 11 2026\n"
    "import platform\n"
    "class CRizomUVLinkBase:\n"
    "\tdef __init__(self):\n"
    "\t\tself.version = 1\n"
    "\n"
    "\tdef Version(self):\n"
    '\t\t""" Returns the version of the RizomUV Link module """\n'
    "\t\treturn self.version\n"
    "\n"
    "\tdef Execute(self, commandName, parameters):\n"
    "\t\treturn None\n"
    "\n"
    "\tdef Alpha(self, params = {}):\n"
    '\t\t"""\n'
    "\t\tDo the alpha thing, e.g. \"Lib.Mesh\" paths. Then more.\n"
    "\t\t\n"
    "\t\tPARAMETER       : PrimType\n"
    "\t\tType            : string\n"
    "\t\tPossible Values :\n"
    "\t\t                 - \"Edge\"\n"
    "\t\t\n"
    "\t\t\n"
    '\t\t"""\n'
    "\t\treturn self.Execute('Alpha', params)\n"
    "\n"
    "\tdef Beta(self, params = {}):\n"
    '\t\t""" One-liner doc """\n'
    "\t\treturn self.Execute('Beta', params)\n"
    "\n"
    "\tdef Gamma(self, params = {}):\n"
    "\t\treturn self.Execute('Gamma', params)\n"
)


def test_parses_a_generated_module():
    parsed = docs.parse_module_text(GENERATED)
    assert list(parsed) == ["Alpha", "Beta", "Gamma"]  # skeleton methods skipped, file order kept
    assert parsed["Alpha"].splitlines()[0] == 'Do the alpha thing, e.g. "Lib.Mesh" paths. Then more.'
    assert "PARAMETER       : PrimType" in parsed["Alpha"]
    assert '                 - "Edge"' in parsed["Alpha"]  # inner alignment survives the dedent
    assert not parsed["Alpha"].endswith("\n")
    assert parsed["Beta"] == "One-liner doc"
    assert parsed["Gamma"] == ""
    assert docs.module_version(GENERATED) == "2027.0.486.gf16af8f9"


@pytest.mark.parametrize("variant", ["crlf", "cr", "mixed", "spaces"])
def test_line_endings_and_indentation_do_not_matter(variant):
    text = GENERATED
    if variant == "crlf":
        text = text.replace("\n", "\r\n")
    elif variant == "cr":
        text = text.replace("\n", "\r")
    elif variant == "mixed":
        lines = text.split("\n")
        text = "".join(ln + ("\r\n" if i % 2 else "\n") for i, ln in enumerate(lines))
    else:
        text = text.replace("\t", "    ")
    assert docs.parse_module_text(text) == docs.parse_module_text(GENERATED)


def test_summary_line():
    assert docs.summary_line('Do the alpha thing, e.g. "Lib.Mesh" paths. Then more.') == \
        'Do the alpha thing, e.g. "Lib.Mesh" paths.'
    assert docs.summary_line("\n\nUndo last command\n") == "Undo last command"
    assert docs.summary_line("") == ""
    long = "word " * 100
    s = docs.summary_line(long)
    assert len(s) <= 200 and s.endswith("...")


@pytest.fixture(scope="module")
def shipped():
    path = docs.shipped_module_path()
    if path is None:
        pytest.skip("RizomUVLinkBase.py is not next to the package")
    return path


def test_shipped_module(shipped):
    assert shipped.name == "RizomUVLinkBase.py"
    parsed = docs.parse_module_file(shipped)
    assert len(parsed) == 60
    assert not docs.SKELETON & set(parsed)
    for name in ("Load", "Unfold", "Pack", "Save", "Get", "Undo", "Quit", "Weld"):
        assert name in parsed
    assert parsed["Count"].startswith("Return the number of child items")
    assert "PARAMETER" in parsed["Pack"]
    assert all(doc for doc in parsed.values())
    assert all(not doc.startswith(("\t", " ")) for doc in parsed.values())
    json.dumps(parsed)
    text = shipped.read_text(encoding="utf-8")
    assert docs.module_version(text)


def test_shipped_module_reparsed_as_freshly_generated(shipped):
    """GenPythonModule writes tabs and LF; the shipped copy has mixed endings. Same result."""
    text = shipped.read_text(encoding="utf-8")
    fresh = text.replace("\r\n", "\n")
    assert docs.parse_module_text(fresh) == docs.parse_module_file(shipped)
