"""Command documentation parsed from a generated RizomUVLinkBase.py.

The only complete, per-build source of the command docs is the Python client module
RizomUV generates (`GenPythonModule({"Path": tmp})`, 37 ms, all commands): each command is
a `def Name(self, params = {}):` whose docstring is the command's help. The copy shipped
next to the binding is the fallback when no RizomUV is connected; it is regenerated only on
demand, so it can lag the app. `GenerateScriptingHelp` returns nothing over the link.

The generator indents with tabs and the shipped file carries mixed line endings; both are
normalised here, and a space-indented file parses the same way.
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

# The hand-written skeleton of CRizomUVLinkBase, not RizomUV commands.
SKELETON = frozenset({"__init__", "Version", "RizomUVVersion", "Execute", "Connect", "TCPPortIsOpen",
                      "NotifyConnect", "NotifyPoll", "StartNotificationListener"})

_DEF = re.compile(r"^[ \t]+def (?P<name>[A-Za-z_]\w*)\(self,\s*params\s*=\s*\{\}\)\s*:\s*$")
_VERSION = re.compile(r"File generated by RizomUV (?P<version>\S+)")
_SENTENCE = re.compile(r"(.+?[.!?])(?=\s+[A-Z]|\s*$)")


def shipped_module_path() -> Path | None:
    """The RizomUVLinkBase.py shipped with the binding (the package above mcp/), if present."""
    path = Path(__file__).resolve().parents[2] / "RizomUVLinkBase.py"
    return path if path.is_file() else None


def module_version(text: str) -> str | None:
    """The RizomUV version stamped in a generated module's header."""
    m = _VERSION.search(text[:2000])
    return m.group("version") if m else None


def parse_module_file(path) -> dict[str, str]:
    return parse_module_text(Path(path).read_text(encoding="utf-8", errors="replace"))


def parse_module_text(text: str) -> dict[str, str]:
    """{command name: dedented docstring} for every command method, in file order."""
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    docs = {}
    i = 0
    while i < len(lines):
        m = _DEF.match(lines[i])
        i += 1
        if not m or m.group("name") in SKELETON:
            continue
        j = i
        while j < len(lines) and not lines[j].strip():
            j += 1
        doc = ""
        head = lines[j].lstrip() if j < len(lines) else ""
        if head.startswith('"""'):
            first = head[3:]
            if '"""' in first:
                body, i = [first[:first.index('"""')]], j + 1
            else:
                body = [first]
                j += 1
                while j < len(lines) and '"""' not in lines[j]:
                    body.append(lines[j])
                    j += 1
                if j < len(lines):
                    body.append(lines[j][:lines[j].index('"""')])
                i = j + 1
            doc = _clean(body)
        docs[m.group("name")] = doc
    return docs


def _clean(body):
    first, rest = body[0].strip(), textwrap.dedent("\n".join(body[1:]))
    lines = ([first] if first else []) + [ln.rstrip() for ln in rest.split("\n")]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def summary_line(doc: str, limit: int = 200) -> str:
    """The first sentence of a command doc, for listings."""
    first = next((ln.strip() for ln in doc.splitlines() if ln.strip()), "")
    m = _SENTENCE.match(first)
    text = m.group(1) if m else first
    if len(text) > limit:
        text = text[:limit - 3].rstrip() + "..."
    return text
